### ISSUE TITLE
Is there any dependency for this Application

### ISSUE THREAD

**Issue by saurendra** [ithinkso117/DotNetPusher#9]
I am getting a exception Like this
************** Exception Text **************
DotNetPusher.PusherException
   at DotNetPusher.Pushers.Pusher.StartPush(String url, Int32 width, Int32 height, Int32 frameRate) in E:\xxxxx\xxxx\\DotNetPusher\Pushers\Pusher.cs:line 36
   at StreamWinform.StreamForm.StartPushStream() in E:\xxxxx\xxxx\\StreamWinform\StreamForm.cs:line 75
   at StreamWinform.StreamForm.BtnStreamStart_Click(Object sender, EventArgs e) in E:\xxxxx\xxxx\StreamWinform\StreamForm.cs:line 175
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by saurendra** [comment]
I am getting the exception while running build it in other system.

**Comment by saurendra** [comment]
Please Help Me

**Comment by ithinkso117** [comment]
Have you copied all ffmpeg dlls into the same folder of the application?
